/* SystemJS module definition */
declare var module: NodeModule;
interface NodeModule {
  id: string;
}
declare var firebase: FireBase;

interface FireBase{  
    __esModule: boolean,
    initializeApp: Function,
    app: Function,
    apps: Array<any>,
    Promise: Function,
    SDK_VERSION: string,
    INTERNAL: any,
    default: any,
    auth: Function,
    User: Function,
    database: Function,
    messaging: Function,
    storage: Function,

}
declare var firebaseconfig: FireBaseConfig;

interface FireBaseConfig{
  apiKey:string,
  authDomain:string,
  databaseURL:string,
  projectId:string,
  storageBucket:string,
  messagingSenderId:string
}

declare var chart: Highcharts;
interface Highcharts{
  
    product: string,
    version: string,
    deg2rad: number,
    doc: any,
    hasBidiBug: boolean,
    hasTouch: boolean,
    isMS: boolean,
    isWebKit: boolean,
    isFirefox: boolean,
    isTouchDevice: boolean,
    SVG_NS: string,
    chartCount: number,
    seriesTypes: any,
    symbolSizes: any,
    svg: boolean,
    win: any,
    marginNames: any,
    noop: Function,
    charts: any,
    timers: any,
    error: Function,
    Fx: Function,
    extend: Function,
    merge: Function,
    pInt: Function,
    isString: Function,
    isArray: Function,
    isObject: Function,
    isDOMElement: Function,
    isClass: Function,
    isNumber: Function,
    erase: Function,
    defined: Function,
    attr: Function,
    splat: Function,
    syncTimeout: Function,
    pick: Function,
    css: Function,
    createElement: Function,
    extendClass: Function,
    pad: Function,
    relativeLength: Function,
    wrap: Function,
    getTZOffset: Function,
    dateFormat: Function,
    formatSingle: Function,
    format: Function,
    getMagnitude: Function,
    normalizeTickInterval: Function,
    stableSort: Function,
    arrayMin: Function,
    arrayMax: Function,
    destroyObjectProperties: Function,
    discardElement: Function,
    correctFloat: Function,
    setAnimation: Function,
    animObject: Function,
    timeUnits: any,
    numberFormat: Function,
    getStyle: Function,
    inArray: Function,
    grep: Function,
    find: Function,
    map: Function,
    keys: Function,
    reduce: Function,
    offset: Function,
    stop: Function,
    each: Function,
    objectEach: Function,
    addEvent: Function,
    removeEvent: Function,
    fireEvent: Function,
    animate: Function,
    seriesType: Function,
    uniqueKey: Function,
    Color: Function,
    color: Function,
    SVGElement: Function,
    SVGRenderer: Function,
    Renderer: Function,
    defaultOptions: any,
    setOptions: Function,
    getOptions: Function,
    defaultPlotOptions: any,
    Date: Function,
    Tick: Function,
    Axis: Function,
    PlotLineOrBand: Function,
    Tooltip: Function,
    Pointer: Function,
    Legend: Function,
    LegendSymbolMixin: any,
    Chart: Function,
    chart: Function,
    Point: Function,
    Series: Function,
    StackItem: Function,
    CenteredSeriesMixin: any,
    distribute: Function,
    TrackerMixin: any

}